import Footers from "@/components/others/footers";
import Nav from "@/components/others/nav";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "loja",
  description: "Generated by create next app",
};

export default function LayoutDashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav />
      <div className="">{children}</div>

      <Footers />
    </>
  );
}
